export { About } from './About'
export { EditProfile } from './EditProfile'
export { Feed } from './Feed'
export { Forgot } from './Forgot'
export { Home } from './Home'
export { Login } from './Login'
export { Profile } from './Profile'
export { Register } from './Register'
